#!/usr/bin/env python
import argparse

import core.fab

from core import shared


def main():
    proj_config = shared.read_config(repo_aliasing=False)

    parser = argparse.ArgumentParser(description='Deploy the latest build.')
    parser.add_argument('--app', dest='app_name', choices=proj_config.keys(), required=True)
    args = parser.parse_args()

    core.fab.deploy(args.app_name, proj_config[args.app_name])


if __name__ == '__main__':
    main()
