#!/usr/bin/env python
import argparse

from core import shared


def main():
    proj_config = shared.read_config()

    parser = argparse.ArgumentParser(description='Remove one or more configuration variables.')
    parser.add_argument('--app', dest='app_name', choices=proj_config.keys(), required=True)
    parser.add_argument('remove_keys', nargs='+', metavar='KEY')
    args = parser.parse_args()
    remove_keys = args.remove_keys

    app_name = args.app_name
    build_repo = shared.get_user_build_repo(app_name, proj_config[app_name])
    config_vars = build_repo.get_config_vars()

    config_vars = [v for v in config_vars if v[0] not in remove_keys]

    build_repo.set_config_vars(config_vars)
    print 'Done.'


if __name__ == '__main__':
    main()
