#!/usr/bin/env python
from core import cottonargparser
from core import shared


def main():
    proj_config = shared.read_config()

    parser = cottonargparser.CottonArgParser(
        proj_config,
        description='Add one or more configuration variables.'
    )
    parser.add_argument('new_vars', nargs='+', metavar='KEY=value')
    args = parser.parse_args()

    new_vars = [arg.split('=') for arg in args.new_vars]
    new_keys = [v[0] for v in new_vars]

    app_name = args.app_name
    build_repo = shared.get_user_build_repo(app_name, proj_config[app_name])
    config_vars = build_repo.get_config_vars()

    # Remove existing entries.
    config_vars = [v for v in config_vars if v[0] not in new_keys]

    # Append new entries.
    config_vars = config_vars + new_vars

    build_repo.set_config_vars(config_vars)
    print 'Done.'


if __name__ == '__main__':
    main()
