#!/usr/bin/env python
import core.fab

from core import cottonargparser
from core import shared


def main():
    proj_config = shared.read_config(repo_aliasing=False)

    parser = cottonargparser.CottonArgParser(
        proj_config,
        description='Deploy the latest build.'
    )
    args = parser.parse_args()

    core.fab.deploy(args.app_name, proj_config[args.app_name])


if __name__ == '__main__':
    main()
