#!/usr/bin/env python
import argparse

import core.fab

from core import cottonargparser
from core import shared


def main():
    proj_config = shared.read_config(repo_aliasing=False)

    parser = cottonargparser.CottonArgParser(
        proj_config,
        description='Run a command on a server.'
    )
    parser.add_argument('command', nargs=argparse.REMAINDER)
    args = parser.parse_args()

    if not args.command:
        print 'Invalid command.'
        return

    command = ' '.join(args.command)
    core.fab.run_command(args.app_name, proj_config[args.app_name], command)


if __name__ == '__main__':
    main()
